// Autogenerated by jnigen. DO NOT EDIT!

#include <stdint.h>
#include "jni.h"
#include "dartjni.h"

thread_local JNIEnv *jniEnv;
JniContext *jni;

JniContext *(*context_getter)(void);
JNIEnv *(*env_getter)(void);

void setJniGetters(JniContext *(*cg)(void),
        JNIEnv *(*eg)(void)) {
    context_getter = cg;
    env_getter = eg;
}

// dev.dart.CodeUmlJava
jclass _c_CodeUmlJava = NULL;

jmethodID _m_CodeUmlJava__ctor = NULL;
FFI_PLUGIN_EXPORT
JniResult CodeUmlJava__ctor() {
    load_env();
        load_class_global_ref(&_c_CodeUmlJava, "dev/dart/CodeUmlJava");
    if (_c_CodeUmlJava == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_CodeUmlJava,
      &_m_CodeUmlJava__ctor, "<init>", "()V");
    if (_m_CodeUmlJava__ctor == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->NewObject(jniEnv, _c_CodeUmlJava, _m_CodeUmlJava__ctor);
    return to_global_ref_result(_result);
}

jmethodID _m_CodeUmlJava__getSvg = NULL;
FFI_PLUGIN_EXPORT
JniResult CodeUmlJava__getSvg(jobject text) {
    load_env();
        load_class_global_ref(&_c_CodeUmlJava, "dev/dart/CodeUmlJava");
    if (_c_CodeUmlJava == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_CodeUmlJava,
      &_m_CodeUmlJava__getSvg, "getSvg", "(Ljava/lang/String;)Ljava/lang/Object;");
    if (_m_CodeUmlJava__getSvg == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallStaticObjectMethod(jniEnv, _c_CodeUmlJava, _m_CodeUmlJava__getSvg, text);
    return to_global_ref_result(_result);
}

